[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "quantecon_lib"
version = "0.1.0"
# Package names must be strings!
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["src"]
